name: Serverless Prod Deployment
on:
  push:
    branches:
      - "main"
      - "master"
concurrency:
  group: ${{ github.ref }}/deploy
  cancel-in-progress: true
env:
  DAGSTER_CLOUD_URL: "http://census.dagster.cloud"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  ENABLE_FAST_DEPLOYS: 'true'
  PYTHON_VERSION: '3.10'
jobs:
  deploy:
    name: Deploy to Dagster Cloud
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Dagster Cloud CLI
        run: pip install dagster-cloud
      
      - name: Deploy to Dagster Cloud Serverless
        run: |
          echo "Deploying to Dagster Cloud Serverless"
          dagster-cloud serverless deploy-python-executable ./project-repo \
            --module-name=pipelines.orchestration.dagster_defs \
            --location-name=census-data \
            --api-token=${{ secrets.DAGSTER_CLOUD_API_TOKEN }} \
            --organization=${{ secrets.ORGANIZATION_ID }} \
            --deployment=prod \
            --python-version=${{ env.PYTHON_VERSION }}
